### ISSUE TITLE
Craft drifts away from landing zone

### ISSUE THREAD

**Issue by Aria-NL** [QuasyMoFo/Starship#1]
I used the existing craft, with no changes to the script apart from changing the latitude and longitude of the landing zone. When the craft reached apogee, it simply drifted down with no movement. This resulted in the landing point being several hundred meters from the specified landing zone. In this case, the landing zone was just next to the launch pad, well within the limits of Starship. Additionally, just before touchdown, the craft tends to try and tip over slightly, causing instability after landing. I am running KSRSS 2.5x, which may contribute to the issue.

**Comment by QuasyMoFo** [comment]
There should be a variable called lngErrorMulti and it's -175 in one case with 175 in the other case, try messing around with this variable and you can fine tune the steering aspect.

Also, i think at lines 168 and 174, there are 2 variables
`lock lngCorrection to (lngerror() * lngerrormulti*5) or whatever
change the bit at the end from *5 to whatever works best, thanks!
